#!/bin/bash
# Script para preparar archivos para PythonAnywhere

echo "========================================="
echo "PREPARACIÓN PARA PYTHONANYWHERE"
echo "========================================="

echo "1. Archivos a subir a PythonAnywhere:"
echo "   - app_pythonanywhere.py (como app.py)"
echo "   - db-microservice/wsgi.py"
echo "   - requirements.txt"
echo "   - db-microservice/init_complete_db.py"

echo ""
echo "2. Carpeta de imágenes:"
echo "   - public/images/products/ (todas las imágenes de productos)"

echo ""
echo "3. Pasos en PythonAnywhere:"
echo ""
echo "   a) Crear una nueva Web App:"
echo "      - Framework: Manual configuration"
echo "      - Python version: 3.10"
echo ""
echo "   b) Configurar directorios:"
echo "      - Source code: /home/exael/tienda-abarrotes-react"
echo "      - Working directory: /home/exael/tienda-abarrotes-react"
echo ""
echo "   c) Editar WSGI file (/var/www/exael_pythonanywhere_com_wsgi.py):"
echo "      - Usar app_pythonanywhere.py como aplicación principal"
echo ""
echo "   d) Instalar dependencias en la consola de PythonAnywhere:"
echo "      cd ~/tienda-abarrotes-react"
echo "      pip3.10 install --user -r requirements.txt"
echo ""
echo "   e) Inicializar base de datos completa:"
echo "      cd ~/tienda-abarrotes-react/db-microservice"
echo "      python3.10 init_complete_db.py"
echo ""
echo "   f) Tu API estará disponible en:"
echo "      https://exael.pythonanywhere.com/api/products"
echo "      Usuario de prueba: exael / exael"

echo ""
echo "4. Script automático de deployment:"
echo "   En PythonAnywhere, ejecuta:"
echo "   bash deploy.sh"
echo ""
echo "   Esto automatiza:"
echo "   - git pull origin main"
echo "   - npm run build"  
echo "   - Copia app_pythonanywhere.py a db-microservice/app.py"
echo "   - Ejecuta init_complete_db.py"

echo ""
echo "========================================="
echo "NOTAS IMPORTANTES:"
echo "========================================="
echo "- init_complete_db.py crea TODAS las tablas necesarias:"
echo "  * productos (con 28 productos de ejemplo)"
echo "  * users (con usuario exael/exael)"
echo "  * user_sessions (para autenticación JWT)" 
echo "  * cart_items (para persistencia del carrito)"
echo ""
echo "- No necesitas subir db.sqlite3 manualmente"
echo "- La base de datos se crea automáticamente en deployment"
echo "- app_pythonanywhere.py tiene configuración optimizada para producción"

echo ""
echo "========================================="
echo "¡LISTO PARA DEPLOY!"
echo "========================================="