#!/bin/bash
# Script para preparar archivos para PythonAnywhere

echo "========================================="
echo "PREPARACIÓN PARA PYTHONANYWHERE"
echo "========================================="

echo "1. Archivos a subir a PythonAnywhere:"
echo "   - db-microservice/app.py"
echo "   - db-microservice/wsgi.py"
echo "   - db-microservice/requirements.txt"
echo "   - db-microservice/update_products.py"
echo "   - db-microservice/db.sqlite3"

echo ""
echo "2. Carpeta de imágenes:"
echo "   - public/images/products/ (todas las imágenes de productos)"

echo ""
echo "3. Pasos en PythonAnywhere:"
echo ""
echo "   a) Crear una nueva Web App:"
echo "      - Framework: Manual configuration"
echo "      - Python version: 3.10"
echo ""
echo "   b) Configurar directorios:"
echo "      - Source code: /home/tuusuario/tienda-abarrotes/db-microservice"
echo "      - Working directory: /home/tuusuario/tienda-abarrotes/db-microservice"
echo ""
echo "   c) Editar WSGI file (/var/www/tuusuario_pythonanywhere_com_wsgi.py):"
echo "      - Copiar el contenido de wsgi.py"
echo "      - Cambiar 'tuusuario' por tu nombre de usuario real"
echo ""
echo "   d) Instalar dependencias en la consola de PythonAnywhere:"
echo "      cd ~/tienda-abarrotes/db-microservice"
echo "      pip3.10 install --user -r requirements.txt"
echo ""
echo "   e) Ejecutar script de población de BD:"
echo "      python3.10 update_products.py"
echo ""
echo "   f) Tu API estará disponible en:"
echo "      https://tuusuario.pythonanywhere.com/api/products"

echo ""
echo "4. Actualizar frontend para usar la nueva URL:"
echo "   - Cambiar API_URL en src/services/api.js"
echo "   - De: http://localhost:5000/api"
echo "   - A: https://tuusuario.pythonanywhere.com/api"

echo ""
echo "========================================="
echo "¡LISTO PARA DEPLOY!"
echo "========================================="